//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netpack.GatewayDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleLogs() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netpack.GatewayDashboard.Resources.ConsoleLogs", typeof(ConsoleLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to initialize.
        /// </summary>
        public static string ConsoleLogsFailedToInitialize {
            get {
                return ResourceManager.GetString("ConsoleLogsFailedToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished watching logs.
        /// </summary>
        public static string ConsoleLogsFinishedWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsFinishedWatchingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Console logs.
        /// </summary>
        public static string ConsoleLogsHeader {
            get {
                return ResourceManager.GetString("ConsoleLogsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing log viewer....
        /// </summary>
        public static string ConsoleLogsInitializingLogViewer {
            get {
                return ResourceManager.GetString("ConsoleLogsInitializingLogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading resources ....
        /// </summary>
        public static string ConsoleLogsLoadingResources {
            get {
                return ResourceManager.GetString("ConsoleLogsLoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logs not yet available.
        /// </summary>
        public static string ConsoleLogsLogsNotYetAvailable {
            get {
                return ResourceManager.GetString("ConsoleLogsLogsNotYetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No resource selected.
        /// </summary>
        public static string ConsoleLogsNoResourceSelected {
            get {
                return ResourceManager.GetString("ConsoleLogsNoResourceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} console logs.
        /// </summary>
        public static string ConsoleLogsPageTitle {
            get {
                return ResourceManager.GetString("ConsoleLogsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select resource.
        /// </summary>
        public static string ConsoleLogsSelectResourceToolbar {
            get {
                return ResourceManager.GetString("ConsoleLogsSelectResourceToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown state.
        /// </summary>
        public static string ConsoleLogsUnknownState {
            get {
                return ResourceManager.GetString("ConsoleLogsUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watching logs....
        /// </summary>
        public static string ConsoleLogsWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsWatchingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service log status.
        /// </summary>
        public static string LogStatusLabel {
            get {
                return ResourceManager.GetString("LogStatusLabel", resourceCulture);
            }
        }
    }
}
