//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netpack.GatewayDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netpack.GatewayDashboard.Resources.ControlsStrings", typeof(ControlsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string ActionsButtonText {
            get {
                return ResourceManager.GetString("ActionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string ActionsColumnHeader {
            get {
                return ResourceManager.GetString("ActionsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Structured logs.
        /// </summary>
        public static string ActionStructuredLogsText {
            get {
                return ResourceManager.GetString("ActionStructuredLogsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View details.
        /// </summary>
        public static string ActionViewDetailsText {
            get {
                return ResourceManager.GetString("ActionViewDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на application.
        /// </summary>
        public static string ApplicationLower {
            get {
                return ResourceManager.GetString("ApplicationLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All tags.
        /// </summary>
        public static string ChartContainerAllTags {
            get {
                return ResourceManager.GetString("ChartContainerAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filtered tags.
        /// </summary>
        public static string ChartContainerFilteredTags {
            get {
                return ResourceManager.GetString("ChartContainerFilteredTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        public static string ChartContainerFiltersHeader {
            get {
                return ResourceManager.GetString("ChartContainerFiltersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph. For an accessible view please navigate to the Table tab.
        /// </summary>
        public static string ChartContainerGraphAccessibleLabel {
            get {
                return ResourceManager.GetString("ChartContainerGraphAccessibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph.
        /// </summary>
        public static string ChartContainerGraphTab {
            get {
                return ResourceManager.GetString("ChartContainerGraphTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string ChartContainerOptionsHeader {
            get {
                return ResourceManager.GetString("ChartContainerOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select filters.
        /// </summary>
        public static string ChartContainerSelectFilters {
            get {
                return ResourceManager.GetString("ChartContainerSelectFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show count.
        /// </summary>
        public static string ChartContainerShowCountLabel {
            get {
                return ResourceManager.GetString("ChartContainerShowCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        public static string ChartContainerTableTab {
            get {
                return ResourceManager.GetString("ChartContainerTableTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to display chart.
        /// </summary>
        public static string ChartContainerUnableToDisplay {
            get {
                return ResourceManager.GetString("ChartContainerUnableToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string DetailsColumnHeader {
            get {
                return ResourceManager.GetString("DetailsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration.
        /// </summary>
        public static string DurationColumnHeader {
            get {
                return ResourceManager.GetString("DurationColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show all.
        /// </summary>
        public static string EnvironmentVariablesFilterToggleShowAll {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFilterToggleShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show spec only.
        /// </summary>
        public static string EnvironmentVariablesFilterToggleShowSpecOnly {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFilterToggleShowSpecOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide values.
        /// </summary>
        public static string EnvironmentVariablesHideVariableValues {
            get {
                return ResourceManager.GetString("EnvironmentVariablesHideVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show values.
        /// </summary>
        public static string EnvironmentVariablesShowVariableValues {
            get {
                return ResourceManager.GetString("EnvironmentVariablesShowVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event.
        /// </summary>
        public static string EventColumnHeader {
            get {
                return ResourceManager.GetString("EventColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception details.
        /// </summary>
        public static string ExceptionDetailsTitle {
            get {
                return ResourceManager.GetString("ExceptionDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter....
        /// </summary>
        public static string FilterPlaceholder {
            get {
                return ResourceManager.GetString("FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resize.
        /// </summary>
        public static string FluentDataGridHeaderCellResizeButtonText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellResizeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column width (in pixels).
        /// </summary>
        public static string FluentDataGridHeaderCellResizeLabel {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellResizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort (ascending).
        /// </summary>
        public static string FluentDataGridHeaderCellSortAscendingButtonText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellSortAscendingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort.
        /// </summary>
        public static string FluentDataGridHeaderCellSortButtonText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellSortButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort (descending).
        /// </summary>
        public static string FluentDataGridHeaderCellSortDescendingButtonText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellSortDescendingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copied!.
        /// </summary>
        public static string GridValueCopied {
            get {
                return ResourceManager.GetString("GridValueCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy to clipboard.
        /// </summary>
        public static string GridValueCopyToClipboard {
            get {
                return ResourceManager.GetString("GridValueCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide value.
        /// </summary>
        public static string GridValueMaskHideValue {
            get {
                return ResourceManager.GetString("GridValueMaskHideValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show value.
        /// </summary>
        public static string GridValueMaskShowValue {
            get {
                return ResourceManager.GetString("GridValueMaskShowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (All).
        /// </summary>
        public static string LabelAll {
            get {
                return ResourceManager.GetString("LabelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Empty).
        /// </summary>
        public static string LabelEmpty {
            get {
                return ResourceManager.GetString("LabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (None).
        /// </summary>
        public static string LabelNone {
            get {
                return ResourceManager.GetString("LabelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Unset).
        /// </summary>
        public static string LabelUnset {
            get {
                return ResourceManager.GetString("LabelUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exemplars.
        /// </summary>
        public static string MetricTableExemplarsColumnHeader {
            get {
                return ResourceManager.GetString("MetricTableExemplarsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No metrics data found.
        /// </summary>
        public static string MetricTableNoMetricsFound {
            get {
                return ResourceManager.GetString("MetricTableNoMetricsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show latest 10 values.
        /// </summary>
        public static string MetricTableShowLatestValues {
            get {
                return ResourceManager.GetString("MetricTableShowLatestValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only show value updates.
        /// </summary>
        public static string MetricTableShowOnlyValueChanges {
            get {
                return ResourceManager.GetString("MetricTableShowOnlyValueChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string MetricTableStartColumnHeader {
            get {
                return ResourceManager.GetString("MetricTableStartColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value decreased.
        /// </summary>
        public static string MetricTableValueDecreased {
            get {
                return ResourceManager.GetString("MetricTableValueDecreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value increased.
        /// </summary>
        public static string MetricTableValueIncreased {
            get {
                return ResourceManager.GetString("MetricTableValueIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value did not change.
        /// </summary>
        public static string MetricTableValueNoChange {
            get {
                return ResourceManager.GetString("MetricTableValueNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View exemplars.
        /// </summary>
        public static string MetricTableViewExemplarsLabel {
            get {
                return ResourceManager.GetString("MetricTableViewExemplarsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string NameColumnHeader {
            get {
                return ResourceManager.GetString("NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page toolbar.
        /// </summary>
        public static string PageToolbarLandmark {
            get {
                return ResourceManager.GetString("PageToolbarLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count.
        /// </summary>
        public static string PlotlyChartCount {
            get {
                return ResourceManager.GetString("PlotlyChartCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exemplars.
        /// </summary>
        public static string PlotlyChartExemplars {
            get {
                return ResourceManager.GetString("PlotlyChartExemplars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length.
        /// </summary>
        public static string PlotlyChartLength {
            get {
                return ResourceManager.GetString("PlotlyChartLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string PlotlyChartTime {
            get {
                return ResourceManager.GetString("PlotlyChartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace.
        /// </summary>
        public static string PlotlyChartTrace {
            get {
                return ResourceManager.GetString("PlotlyChartTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string PlotlyChartValue {
            get {
                return ResourceManager.GetString("PlotlyChartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string PropertyGridValueColumnHeader {
            get {
                return ResourceManager.GetString("PropertyGridValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Endpoints.
        /// </summary>
        public static string ResourceDetailsEndpointsHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsEndpointsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Environment variables.
        /// </summary>
        public static string ResourceDetailsEnvironmentVariablesHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsEnvironmentVariablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource.
        /// </summary>
        public static string ResourceDetailsResourceHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsResourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volumes.
        /// </summary>
        public static string ResourceDetailsVolumesHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsVolumesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} (replica of {1}).
        /// </summary>
        public static string ResourceDropdownReplicaAccessibleTitle {
            get {
                return ResourceManager.GetString("ResourceDropdownReplicaAccessibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Health checks.
        /// </summary>
        public static string ResourceHealthChecksHeader {
            get {
                return ResourceManager.GetString("ResourceHealthChecksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource.
        /// </summary>
        public static string ResourceLabel {
            get {
                return ResourceManager.GetString("ResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an application.
        /// </summary>
        public static string SelectAnApplication {
            get {
                return ResourceManager.GetString("SelectAnApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backlinks.
        /// </summary>
        public static string SpanDetailsBacklinksHeader {
            get {
                return ResourceManager.GetString("SpanDetailsBacklinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Context.
        /// </summary>
        public static string SpanDetailsContextHeader {
            get {
                return ResourceManager.GetString("SpanDetailsContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string SpanDetailsDetailsColumnHeader {
            get {
                return ResourceManager.GetString("SpanDetailsDetailsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string SpanDetailsDuration {
            get {
                return ResourceManager.GetString("SpanDetailsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Events.
        /// </summary>
        public static string SpanDetailsEventsHeader {
            get {
                return ResourceManager.GetString("SpanDetailsEventsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Links.
        /// </summary>
        public static string SpanDetailsLinksHeader {
            get {
                return ResourceManager.GetString("SpanDetailsLinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string SpanDetailsResource {
            get {
                return ResourceManager.GetString("SpanDetailsResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource.
        /// </summary>
        public static string SpanDetailsResourceHeader {
            get {
                return ResourceManager.GetString("SpanDetailsResourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Span.
        /// </summary>
        public static string SpanDetailsSpanColumnHeader {
            get {
                return ResourceManager.GetString("SpanDetailsSpanColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Span.
        /// </summary>
        public static string SpanDetailsSpanHeader {
            get {
                return ResourceManager.GetString("SpanDetailsSpanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Span.
        /// </summary>
        public static string SpanDetailsSpanPrefix {
            get {
                return ResourceManager.GetString("SpanDetailsSpanPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start time &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string SpanDetailsStartTime {
            get {
                return ResourceManager.GetString("SpanDetailsStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string StateColumnHeader {
            get {
                return ResourceManager.GetString("StateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add filter.
        /// </summary>
        public static string StructuredFilteringAddFilter {
            get {
                return ResourceManager.GetString("StructuredFilteringAddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        public static string StructuredFilteringFilters {
            get {
                return ResourceManager.GetString("StructuredFilteringFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No filters.
        /// </summary>
        public static string StructuredFilteringNoFilters {
            get {
                return ResourceManager.GetString("StructuredFilteringNoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Context.
        /// </summary>
        public static string StructuredLogsDetailsContextHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception.
        /// </summary>
        public static string StructuredLogsDetailsExceptionHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsExceptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log entry.
        /// </summary>
        public static string StructuredLogsDetailsLogEntryHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsLogEntryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string StructuredLogsDetailsResource {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource.
        /// </summary>
        public static string StructuredLogsDetailsResourceHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsResourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timestamp &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string StructuredLogsDetailsTimestamp {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string SummaryDetailsViewCloseView {
            get {
                return ResourceManager.GetString("SummaryDetailsViewCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Split horizontal.
        /// </summary>
        public static string SummaryDetailsViewSplitHorizontal {
            get {
                return ResourceManager.GetString("SummaryDetailsViewSplitHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Split vertical.
        /// </summary>
        public static string SummaryDetailsViewSplitVertical {
            get {
                return ResourceManager.GetString("SummaryDetailsViewSplitVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time offset.
        /// </summary>
        public static string TimeOffsetColumnHeader {
            get {
                return ResourceManager.GetString("TimeOffsetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timestamp.
        /// </summary>
        public static string TimestampColumnHeader {
            get {
                return ResourceManager.GetString("TimestampColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total: &lt;strong&gt;{0} results found&lt;/strong&gt;.
        /// </summary>
        public static string TotalItemsFooterText {
            get {
                return ResourceManager.GetString("TotalItemsFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attributes.
        /// </summary>
        public static string TraceDetailAttributesHeader {
            get {
                return ResourceManager.GetString("TraceDetailAttributesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string ViewAction {
            get {
                return ResourceManager.GetString("ViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View logs.
        /// </summary>
        public static string ViewLogsLink {
            get {
                return ResourceManager.GetString("ViewLogsLink", resourceCulture);
            }
        }
    }
}
