//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netpack.GatewayDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netpack.GatewayDashboard.Resources.Dialogs", typeof(Dialogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string ExemplarsDialogCloseButtonText {
            get {
                return ResourceManager.GetString("ExemplarsDialogCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string ExemplarsDialogDetailsColumnHeader {
            get {
                return ResourceManager.GetString("ExemplarsDialogDetailsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timestamp.
        /// </summary>
        public static string ExemplarsDialogTimestampColumnHeader {
            get {
                return ResourceManager.GetString("ExemplarsDialogTimestampColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exemplars.
        /// </summary>
        public static string ExemplarsDialogTitle {
            get {
                return ResourceManager.GetString("ExemplarsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace.
        /// </summary>
        public static string ExemplarsDialogTrace {
            get {
                return ResourceManager.GetString("ExemplarsDialogTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace.
        /// </summary>
        public static string ExemplarsDialogTraceColumnHeader {
            get {
                return ResourceManager.GetString("ExemplarsDialogTraceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string ExemplarsDialogValueColumnHeader {
            get {
                return ResourceManager.GetString("ExemplarsDialogValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply filter.
        /// </summary>
        public static string FilterDialogApplyFilterButtonText {
            get {
                return ResourceManager.GetString("FilterDialogApplyFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string FilterDialogCancelButtonText {
            get {
                return ResourceManager.GetString("FilterDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Condition.
        /// </summary>
        public static string FilterDialogConditionInputLabel {
            get {
                return ResourceManager.GetString("FilterDialogConditionInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field.
        /// </summary>
        public static string FilterDialogFieldPlaceholder {
            get {
                return ResourceManager.GetString("FilterDialogFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter.
        /// </summary>
        public static string FilterDialogParameterInputLabel {
            get {
                return ResourceManager.GetString("FilterDialogParameterInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove filter.
        /// </summary>
        public static string FilterDialogRemoveFilterButtonText {
            get {
                return ResourceManager.GetString("FilterDialogRemoveFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string FilterDialogTextValuePlaceholder {
            get {
                return ResourceManager.GetString("FilterDialogTextValuePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Site-wide navigation.
        /// </summary>
        public static string HelpDialogCategoryNavigation {
            get {
                return ResourceManager.GetString("HelpDialogCategoryNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page navigation.
        /// </summary>
        public static string HelpDialogCategoryPageNavigation {
            get {
                return ResourceManager.GetString("HelpDialogCategoryPageNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Panels.
        /// </summary>
        public static string HelpDialogCategoryPanels {
            get {
                return ResourceManager.GetString("HelpDialogCategoryPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease panel size.
        /// </summary>
        public static string HelpDialogDecreasePanelSize {
            get {
                return ResourceManager.GetString("HelpDialogDecreasePanelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Microsoft Learn documentation.
        /// </summary>
        public static string HelpDialogGetHelpLinkText {
            get {
                return ResourceManager.GetString("HelpDialogGetHelpLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Console Logs.
        /// </summary>
        public static string HelpDialogGoToConsoleLogs {
            get {
                return ResourceManager.GetString("HelpDialogGoToConsoleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Help.
        /// </summary>
        public static string HelpDialogGoToHelp {
            get {
                return ResourceManager.GetString("HelpDialogGoToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Metrics.
        /// </summary>
        public static string HelpDialogGoToMetrics {
            get {
                return ResourceManager.GetString("HelpDialogGoToMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Resources.
        /// </summary>
        public static string HelpDialogGoToResources {
            get {
                return ResourceManager.GetString("HelpDialogGoToResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Settings.
        /// </summary>
        public static string HelpDialogGoToSettings {
            get {
                return ResourceManager.GetString("HelpDialogGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Structured Logs.
        /// </summary>
        public static string HelpDialogGoToStructuredLogs {
            get {
                return ResourceManager.GetString("HelpDialogGoToStructuredLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Traces.
        /// </summary>
        public static string HelpDialogGoToTraces {
            get {
                return ResourceManager.GetString("HelpDialogGoToTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase panel size.
        /// </summary>
        public static string HelpDialogIncreasePanelSize {
            get {
                return ResourceManager.GetString("HelpDialogIncreasePanelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyboard Shortcuts.
        /// </summary>
        public static string HelpDialogKeyboardShortcutsTitle {
            get {
                return ResourceManager.GetString("HelpDialogKeyboardShortcutsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset panel sizes.
        /// </summary>
        public static string HelpDialogResetPanelSize {
            get {
                return ResourceManager.GetString("HelpDialogResetPanelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close panel.
        /// </summary>
        public static string HelpDialogTogglePanelOpen {
            get {
                return ResourceManager.GetString("HelpDialogTogglePanelOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle panel orientation.
        /// </summary>
        public static string HelpDialogTogglePanelOrientation {
            get {
                return ResourceManager.GetString("HelpDialogTogglePanelOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in text visualizer.
        /// </summary>
        public static string OpenInTextVisualizer {
            get {
                return ResourceManager.GetString("OpenInTextVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string OpenTraceDialogCancelButtonText {
            get {
                return ResourceManager.GetString("OpenTraceDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting for trace {0} to load....
        /// </summary>
        public static string OpenTraceDialogMessage {
            get {
                return ResourceManager.GetString("OpenTraceDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string SettingsDialogDarkTheme {
            get {
                return ResourceManager.GetString("SettingsDialogDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string SettingsDialogLightTheme {
            get {
                return ResourceManager.GetString("SettingsDialogLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System.
        /// </summary>
        public static string SettingsDialogSystemTheme {
            get {
                return ResourceManager.GetString("SettingsDialogSystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string SettingsDialogTheme {
            get {
                return ResourceManager.GetString("SettingsDialogTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version: {0}.
        /// </summary>
        public static string SettingsDialogVersion {
            get {
                return ResourceManager.GetString("SettingsDialogVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format JSON.
        /// </summary>
        public static string TextVisualizerDialogJsonFormat {
            get {
                return ResourceManager.GetString("TextVisualizerDialogJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unformatted.
        /// </summary>
        public static string TextVisualizerDialogPlaintextFormat {
            get {
                return ResourceManager.GetString("TextVisualizerDialogPlaintextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format XML.
        /// </summary>
        public static string TextVisualizerDialogXmlFormat {
            get {
                return ResourceManager.GetString("TextVisualizerDialogXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select format.
        /// </summary>
        public static string TextVisualizerSelectFormatType {
            get {
                return ResourceManager.GetString("TextVisualizerSelectFormatType", resourceCulture);
            }
        }
    }
}
