//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netpack.GatewayDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netpack.GatewayDashboard.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .NET Aspire.
        /// </summary>
        public static string MainLayoutAspire {
            get {
                return ResourceManager.GetString("MainLayoutAspire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string MainLayoutAspireDashboardHelpLink {
            get {
                return ResourceManager.GetString("MainLayoutAspireDashboardHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .NET Aspire repo.
        /// </summary>
        public static string MainLayoutAspireRepoLink {
            get {
                return ResourceManager.GetString("MainLayoutAspireRepoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MainLayoutLaunchSettings {
            get {
                return ResourceManager.GetString("MainLayoutLaunchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string MainLayoutSettingsDialogClose {
            get {
                return ResourceManager.GetString("MainLayoutSettingsDialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MainLayoutSettingsDialogTitle {
            get {
                return ResourceManager.GetString("MainLayoutSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unhandled error has occurred..
        /// </summary>
        public static string MainLayoutUnhandledErrorMessage {
            get {
                return ResourceManager.GetString("MainLayoutUnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload.
        /// </summary>
        public static string MainLayoutUnhandledErrorReload {
            get {
                return ResourceManager.GetString("MainLayoutUnhandledErrorReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Untrusted apps can send telemetry to the dashboard..
        /// </summary>
        public static string MessageTelemetryBody {
            get {
                return ResourceManager.GetString("MessageTelemetryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More information.
        /// </summary>
        public static string MessageTelemetryLink {
            get {
                return ResourceManager.GetString("MessageTelemetryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telemetry endpoint is unsecured.
        /// </summary>
        public static string MessageTelemetryTitle {
            get {
                return ResourceManager.GetString("MessageTelemetryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Console.
        /// </summary>
        public static string NavMenuConsoleLogsTab {
            get {
                return ResourceManager.GetString("NavMenuConsoleLogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metrics.
        /// </summary>
        public static string NavMenuMetricsTab {
            get {
                return ResourceManager.GetString("NavMenuMetricsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitoring.
        /// </summary>
        public static string NavMenuMonitoringTab {
            get {
                return ResourceManager.GetString("NavMenuMonitoringTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources.
        /// </summary>
        public static string NavMenuResourcesTab {
            get {
                return ResourceManager.GetString("NavMenuResourcesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Structured.
        /// </summary>
        public static string NavMenuStructuredLogsTab {
            get {
                return ResourceManager.GetString("NavMenuStructuredLogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Traces.
        /// </summary>
        public static string NavMenuTracesTab {
            get {
                return ResourceManager.GetString("NavMenuTracesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View filters.
        /// </summary>
        public static string PageLayoutViewFilters {
            get {
                return ResourceManager.GetString("PageLayoutViewFilters", resourceCulture);
            }
        }
    }
}
