//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netpack.GatewayDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Metrics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Metrics() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netpack.GatewayDashboard.Resources.Metrics", typeof(Metrics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metrics.
        /// </summary>
        public static string MetricsHeader {
            get {
                return ResourceManager.GetString("MetricsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string MetricsInsturementDescriptionGridNameColumnHeader {
            get {
                return ResourceManager.GetString("MetricsInsturementDescriptionGridNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instrument.
        /// </summary>
        public static string MetricsInsturementNameGridNameColumnHeader {
            get {
                return ResourceManager.GetString("MetricsInsturementNameGridNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 15 minutes.
        /// </summary>
        public static string MetricsLastFifteenMinutes {
            get {
                return ResourceManager.GetString("MetricsLastFifteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 5 minutes.
        /// </summary>
        public static string MetricsLastFiveMinutes {
            get {
                return ResourceManager.GetString("MetricsLastFiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last hour.
        /// </summary>
        public static string MetricsLastHour {
            get {
                return ResourceManager.GetString("MetricsLastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 1 minute.
        /// </summary>
        public static string MetricsLastOneMinute {
            get {
                return ResourceManager.GetString("MetricsLastOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 6 hours.
        /// </summary>
        public static string MetricsLastSixHours {
            get {
                return ResourceManager.GetString("MetricsLastSixHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 30 minutes.
        /// </summary>
        public static string MetricsLastThirtyMinutes {
            get {
                return ResourceManager.GetString("MetricsLastThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 3 hours.
        /// </summary>
        public static string MetricsLastThreeHours {
            get {
                return ResourceManager.GetString("MetricsLastThreeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 12 hours.
        /// </summary>
        public static string MetricsLastTwelveHours {
            get {
                return ResourceManager.GetString("MetricsLastTwelveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last 24 hours.
        /// </summary>
        public static string MetricsLastTwentyFourHours {
            get {
                return ResourceManager.GetString("MetricsLastTwentyFourHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No metrics for the selected resource.
        /// </summary>
        public static string MetricsNoMetricsForResource {
            get {
                return ResourceManager.GetString("MetricsNoMetricsForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} metrics.
        /// </summary>
        public static string MetricsPageTitle {
            get {
                return ResourceManager.GetString("MetricsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a duration.
        /// </summary>
        public static string MetricsSelectADuration {
            get {
                return ResourceManager.GetString("MetricsSelectADuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a resource to view metrics.
        /// </summary>
        public static string MetricsSelectAResource {
            get {
                return ResourceManager.GetString("MetricsSelectAResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select instrument..
        /// </summary>
        public static string MetricsSelectInstrument {
            get {
                return ResourceManager.GetString("MetricsSelectInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View attributes.
        /// </summary>
        public static string MetricsViewAttributesToolbar {
            get {
                return ResourceManager.GetString("MetricsViewAttributesToolbar", resourceCulture);
            }
        }
    }
}
