//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netpack.GatewayDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netpack.GatewayDashboard.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Console logs.
        /// </summary>
        public static string ResourceActionConsoleLogsText {
            get {
                return ResourceManager.GetString("ResourceActionConsoleLogsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metrics.
        /// </summary>
        public static string ResourceActionMetricsText {
            get {
                return ResourceManager.GetString("ResourceActionMetricsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Structured logs.
        /// </summary>
        public static string ResourceActionStructuredLogsText {
            get {
                return ResourceManager.GetString("ResourceActionStructuredLogsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No telemetry found for this resource..
        /// </summary>
        public static string ResourceActionTelemetryTooltip {
            get {
                return ResourceManager.GetString("ResourceActionTelemetryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Traces.
        /// </summary>
        public static string ResourceActionTracesText {
            get {
                return ResourceManager.GetString("ResourceActionTracesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} &quot;{1}&quot; failed.
        /// </summary>
        public static string ResourceCommandFailed {
            get {
                return ResourceManager.GetString("ResourceCommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} &quot;{1}&quot; starting.
        /// </summary>
        public static string ResourceCommandStarting {
            get {
                return ResourceManager.GetString("ResourceCommandStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} &quot;{1}&quot; succeeded.
        /// </summary>
        public static string ResourceCommandSuccess {
            get {
                return ResourceManager.GetString("ResourceCommandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View console logs.
        /// </summary>
        public static string ResourceCommandToastViewLogs {
            get {
                return ResourceManager.GetString("ResourceCommandToastViewLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Endpoint URL.
        /// </summary>
        public static string ResourceDetailsEndpointUrl {
            get {
                return ResourceManager.GetString("ResourceDetailsEndpointUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy URL.
        /// </summary>
        public static string ResourceDetailsProxyUrl {
            get {
                return ResourceManager.GetString("ResourceDetailsProxyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View console logs.
        /// </summary>
        public static string ResourceDetailsViewConsoleLogs {
            get {
                return ResourceManager.GetString("ResourceDetailsViewConsoleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string ResourcesActionsColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesActionsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container arguments.
        /// </summary>
        public static string ResourcesDetailsContainerArgumentsProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerArgumentsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container command.
        /// </summary>
        public static string ResourcesDetailsContainerCommandProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerCommandProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container ID.
        /// </summary>
        public static string ResourcesDetailsContainerIdProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerIdProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container image.
        /// </summary>
        public static string ResourcesDetailsContainerImageProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerImageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container lifetime.
        /// </summary>
        public static string ResourcesDetailsContainerLifetimeProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerLifetimeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container ports.
        /// </summary>
        public static string ResourcesDetailsContainerPortsProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsContainerPortsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display name.
        /// </summary>
        public static string ResourcesDetailsDisplayNameProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsDisplayNameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Executable arguments.
        /// </summary>
        public static string ResourcesDetailsExecutableArgumentsProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExecutableArgumentsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Executable path.
        /// </summary>
        public static string ResourcesDetailsExecutablePathProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExecutablePathProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process ID.
        /// </summary>
        public static string ResourcesDetailsExecutableProcessIdProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExecutableProcessIdProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working directory.
        /// </summary>
        public static string ResourcesDetailsExecutableWorkingDirectoryProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExecutableWorkingDirectoryProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit code.
        /// </summary>
        public static string ResourcesDetailsExitCodeProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsExitCodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Health state.
        /// </summary>
        public static string ResourcesDetailsHealthStateProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsHealthStateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project path.
        /// </summary>
        public static string ResourcesDetailsProjectPathProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsProjectPathProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start time.
        /// </summary>
        public static string ResourcesDetailsStartTimeProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsStartTimeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string ResourcesDetailsStateProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsStateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop time.
        /// </summary>
        public static string ResourcesDetailsStopTimeProperty {
            get {
                return ResourceManager.GetString("ResourcesDetailsStopTimeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Endpoints.
        /// </summary>
        public static string ResourcesEndpointsColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEndpointsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Environment.
        /// </summary>
        public static string ResourcesEnvironmentColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Environment variables for {0}.
        /// </summary>
        public static string ResourcesEnvironmentVariablesHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources.
        /// </summary>
        public static string ResourcesHeader {
            get {
                return ResourceManager.GetString("ResourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No environment variables.
        /// </summary>
        public static string ResourcesNoEnvironmentVariables {
            get {
                return ResourceManager.GetString("ResourcesNoEnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No resources found.
        /// </summary>
        public static string ResourcesNoResources {
            get {
                return ResourceManager.GetString("ResourcesNoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} resources.
        /// </summary>
        public static string ResourcesPageTitle {
            get {
                return ResourceManager.GetString("ResourcesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource types.
        /// </summary>
        public static string ResourcesResourceTypesHeader {
            get {
                return ResourceManager.GetString("ResourcesResourceTypesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source.
        /// </summary>
        public static string ResourcesSourceColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesSourceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start time.
        /// </summary>
        public static string ResourcesStartTimeColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesStartTimeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string ResourcesStateColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesStateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string ResourcesTypeColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesTypeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type filter: All types visible.
        /// </summary>
        public static string ResourcesTypeFilterAllVisible {
            get {
                return ResourceManager.GetString("ResourcesTypeFilterAllVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type filter: Filtered.
        /// </summary>
        public static string ResourcesTypeFiltered {
            get {
                return ResourceManager.GetString("ResourcesTypeFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting for health data....
        /// </summary>
        public static string WaitingForHealthDataMessage {
            get {
                return ResourceManager.GetString("WaitingForHealthDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting....
        /// </summary>
        public static string WaitingHealthDataStatusMessage {
            get {
                return ResourceManager.GetString("WaitingHealthDataStatusMessage", resourceCulture);
            }
        }
    }
}
