//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netpack.GatewayDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StructuredLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StructuredLogs() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netpack.GatewayDashboard.Resources.StructuredLogs", typeof(StructuredLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log message.
        /// </summary>
        public static string ActionLogMessageText {
            get {
                return ResourceManager.GetString("ActionLogMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A maximum of {0} structured logs are stored. Old structured logs are automatically removed..
        /// </summary>
        public static string MessageExceededLimitBody {
            get {
                return ResourceManager.GetString("MessageExceededLimitBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exceeded structured log limit.
        /// </summary>
        public static string MessageExceededLimitTitle {
            get {
                return ResourceManager.GetString("MessageExceededLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add filter.
        /// </summary>
        public static string StructuredLogsAddFilter {
            get {
                return ResourceManager.GetString("StructuredLogsAddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit filter.
        /// </summary>
        public static string StructuredLogsEditFilter {
            get {
                return ResourceManager.GetString("StructuredLogsEditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log entry details.
        /// </summary>
        public static string StructuredLogsEntryDetails {
            get {
                return ResourceManager.GetString("StructuredLogsEntryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        public static string StructuredLogsFilters {
            get {
                return ResourceManager.GetString("StructuredLogsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Structured logs.
        /// </summary>
        public static string StructuredLogsHeader {
            get {
                return ResourceManager.GetString("StructuredLogsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        public static string StructuredLogsLevelColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsLevelColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        public static string StructuredLogsLevels {
            get {
                return ResourceManager.GetString("StructuredLogsLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        public static string StructuredLogsMessageColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsMessageColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message filter.
        /// </summary>
        public static string StructuredLogsMessageFilter {
            get {
                return ResourceManager.GetString("StructuredLogsMessageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum log level filter.
        /// </summary>
        public static string StructuredLogsMinimumLogFilter {
            get {
                return ResourceManager.GetString("StructuredLogsMinimumLogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No filters.
        /// </summary>
        public static string StructuredLogsNoFilters {
            get {
                return ResourceManager.GetString("StructuredLogsNoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No structured logs found.
        /// </summary>
        public static string StructuredLogsNoLogsFound {
            get {
                return ResourceManager.GetString("StructuredLogsNoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} structured logs.
        /// </summary>
        public static string StructuredLogsPageTitle {
            get {
                return ResourceManager.GetString("StructuredLogsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource.
        /// </summary>
        public static string StructuredLogsResourceColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsResourceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a minimum log level.
        /// </summary>
        public static string StructuredLogsSelectMinimumLogLevel {
            get {
                return ResourceManager.GetString("StructuredLogsSelectMinimumLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timestamp.
        /// </summary>
        public static string StructuredLogsTimestampColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsTimestampColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trace.
        /// </summary>
        public static string StructuredLogsTraceColumnHeader {
            get {
                return ResourceManager.GetString("StructuredLogsTraceColumnHeader", resourceCulture);
            }
        }
    }
}
